<script setup lang="ts">
// Persistent navbar button to download the whole documentation as a single
// Markdown file. The file is generated by scripts/gen-completo.mjs and served
// as a static asset from gitbook/public/.
const HREF = '/tesstrade-docs-completo.md'
</script>

<template>
  <a
    class="download-docs"
    :href="HREF"
    download="tesstrade-docs.md"
    title="Download the entire documentation as a single Markdown file — handy for feeding to an AI assistant"
    aria-label="Download the entire documentation as a single Markdown file"
  >
    <svg
      class="download-docs__icon"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width="16"
      height="16"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
    <span class="download-docs__label">Single .md</span>
  </a>
</template>

<style scoped>
/*
 * Lives in VitePress's `nav-bar-content-after` slot, which renders flush
 * against the appearance toggle. `margin-left` gives the two controls room to
 * breathe so the button reads as a distinct, deliberate CTA — not glued to the
 * toggle in the top-right corner.
 */
.download-docs {
  display: inline-flex;
  align-items: center;
  gap: 7px;
  height: 34px;
  margin-left: 14px;
  padding: 0 15px 0 13px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 17px;
  font-size: 13px;
  font-weight: 600;
  letter-spacing: 0.01em;
  line-height: 1;
  color: var(--vp-c-text-2);
  background-color: var(--vp-c-bg-soft);
  white-space: nowrap;
  /* Soft drop shadow for lift + a faint top highlight for a glassy sheen. */
  box-shadow:
    0 1px 2px rgba(0, 0, 0, 0.05),
    inset 0 1px 0 rgba(255, 255, 255, 0.05);
  transition:
    color 0.25s ease,
    border-color 0.25s ease,
    background-color 0.25s ease,
    box-shadow 0.25s ease,
    transform 0.25s ease;
}

.download-docs:hover {
  color: var(--vp-c-brand-1);
  border-color: var(--vp-c-brand-1);
  background-color: var(--vp-c-brand-soft);
  /* Brand-tinted glow that adapts to light/dark via the live brand color. */
  box-shadow: 0 6px 18px -6px color-mix(in srgb, var(--vp-c-brand-1) 55%, transparent);
  transform: translateY(-1px);
}

.download-docs:active {
  transform: translateY(0);
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.06);
}

.download-docs:focus-visible {
  outline: 2px solid var(--vp-c-brand-1);
  outline-offset: 2px;
}

.download-docs__icon {
  flex-shrink: 0;
  transition: transform 0.25s ease;
}

/* Nudge the arrow down on hover to telegraph "download". */
.download-docs:hover .download-docs__icon {
  transform: translateY(1.5px);
}

/* Collapse to a circular icon-only button on narrow screens to save space. */
@media (max-width: 768px) {
  .download-docs {
    width: 34px;
    margin-left: 8px;
    padding: 0;
    justify-content: center;
    border-radius: 50%;
  }
  .download-docs__label {
    display: none;
  }
}
</style>
