<script setup lang="ts">
// Persistent navbar button to download the whole documentation as a single
// Markdown file. The file is generated by scripts/gen-completo.mjs and served
// as a static asset from gitbook/public/.
const HREF = '/tesstrade-docs-completo.md'
</script>

<template>
  <a
    class="download-docs"
    :href="HREF"
    download="tesstrade-docs.md"
    title="Download the entire documentation as a single Markdown file — handy for feeding to an AI assistant"
    aria-label="Download the entire documentation as a single Markdown file"
  >
    <svg
      class="download-docs__icon"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width="16"
      height="16"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
    <span class="download-docs__label">Single .md</span>
  </a>
</template>

<style scoped>
.download-docs {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  height: 32px;
  padding: 0 12px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
  font-size: 13px;
  font-weight: 500;
  line-height: 1;
  color: var(--vp-c-text-2);
  background-color: var(--vp-c-bg-soft);
  white-space: nowrap;
  transition: color 0.25s, border-color 0.25s, background-color 0.25s;
}

.download-docs:hover {
  color: var(--vp-c-brand-1);
  border-color: var(--vp-c-brand-1);
}

.download-docs__icon {
  flex-shrink: 0;
}

/* Collapse to an icon-only button on narrow screens to save navbar space. */
@media (max-width: 768px) {
  .download-docs {
    padding: 0 8px;
  }
  .download-docs__label {
    display: none;
  }
}
</style>
